<?= $this->doctype(); ?>

<html lang="en">
<head>

    <meta charset="utf-8">

    <?= $this->headTitle('Example application which shows usage of Fields API')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink()
        ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css') ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Fields API example</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url('home') ?>">Track</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="https://github.com/back-2-95/fields-example">GitHub</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">

    <?= $this->content; ?>

    <hr>

    <footer>

        <p>&copy; <?php echo date('Y') ?> fields API</p>

    </footer>

</div>

<?= $this->inlineScript()
    ->prependFile('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js')
    ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js')
    ->prependFile('//cdn.ckeditor.com/4.5.7/standard/ckeditor.js')
; ?>

</body>
</html>
