<?php

$entity_configuration = $this->entity_configuration;
$form = $this->form;

$form->prepare();

?>
<div class="jumbotron">

    <div class="container">

        <h1><?= $entity_configuration->getName() ?></h1>

        <p><?= $entity_configuration->getDescription() ?></p>

    </div>

</div>

<div class="row">

    <div class="col-md-12">

        <?= $this->form()->openTag($form); ?>

        <?php

        /** @var Zend\Form\Element $field */
        foreach ($form as $field):

        ?>

            <div class="form-group">

                <?= ($field->getLabel()) ? $this->formLabel($field) : ''; ?>
                <?= $this->formElement($field); ?>
                <?= $this->formElementErrors($field); ?>

            </div>

        <?php endforeach; ?>

        <?= $this->form()->closeTag($form); ?>

    </div>

</div>